# Generated by Django 2.2.5 on 2019-10-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20191019_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academictraining',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='start_date',
            field=models.DateField(),
        ),
    ]
