# Generated by Django 2.2.5 on 2019-10-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20191019_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmenthistory',
            name='role',
            field=models.CharField(default='Ingeniero de procesos', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='skill1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='skill2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='skill3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='skill4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='skill5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='skill6',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='skill7',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='skill8',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='skill9',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
