# Generated by Django 2.2.5 on 2019-10-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20191019_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.URLField()),
                ('linkedin', models.URLField()),
                ('skype', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='employmenthistory',
            name='github',
        ),
        migrations.RemoveField(
            model_name='employmenthistory',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='employmenthistory',
            name='skype',
        ),
    ]
