# Generated by Django 2.2.5 on 2019-10-20 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20191019_1651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
