# Generated by Django 2.2.5 on 2019-10-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20191020_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenthistory',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
